name: Deploy to FTP Prod
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Create Environment Files
        run: node server.js
        env:
          ANGULAR_ENVIRONMENT_SECRET: '${{ secrets.ANGULAR_ENVIRONMENT_SECRET }}'

      - name: Install dependencies
        run: npm install
      - name: ðŸ”¨ Build Project
        run: npm run build
      - name: ðŸ“‚ Sync assets files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.digimoncard.app
          port: 21
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          local-dir: ./dist/digimon-card-game-collector/assets/
          server-dir: ./public_html/assets/
      - name: ðŸ“‚ Sync server files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.digimoncard.app
          port: 21
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          local-dir: ./dist/digimon-card-game-collector/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/assets/**
            **/dist/digimon-card-game-collector/assets/**
          server-dir: ./public_html/
